# Turns device source files into a C++ header holding them as strings.
#
# Device code is compiled at run time by NVRTC, which means the renderer needs the source
# of its kernels while it is running. Reading them off disk would tie a built binary to
# the checkout it came from, so they are baked in instead: this generates one header
# holding every shared header and kernel, under the names their #include directives use.
#
# Run as: cmake -DSOURCES=... -DBASE_DIR=... -DOUTPUT=... -P embed_device_sources.cmake
#
# The fixed parts are written as bracket arguments. A quoted string would need semicolons
# escaped, and the escape survives into the output as a stray backslash.

set(prologue [==[
// Generated by cmake/embed_device_sources.cmake. Do not edit.
#pragma once

namespace Gpu
{

/** \brief One device source file, under the name its #include directives use. */
struct EmbeddedSource
{
    const char *name;
    const char *source;
};

inline const EmbeddedSource embeddedSources[] = {
]==])

set(epilogue [==[
};

inline constexpr int embeddedSourceCount = static_cast<int>(sizeof(embeddedSources) / sizeof(embeddedSources[0]));

} // namespace Gpu
]==])

set(generated "${prologue}")

foreach(relative ${SOURCES})
    file(READ "${BASE_DIR}/${relative}" contents)

    # A raw string literal ends at its delimiter, so the delimiter has to be one that
    # cannot appear in the file. Nothing here contains this.
    string(APPEND generated "    {\"${relative}\", R\"PTDEVICE(${contents})PTDEVICE\"},\n")
endforeach()

string(APPEND generated "${epilogue}")

file(WRITE "${OUTPUT}" "${generated}")
